--------------------------------------------------------
-- Archivo creado  - sábado-septiembre-11-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence AUTOR_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "NEXOSUSER"."AUTOR_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence LIBRO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "NEXOSUSER"."LIBRO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table Autors
--------------------------------------------------------

  CREATE TABLE "NEXOSUSER"."Autors" 
   (	"Idautor" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"Nombre" NVARCHAR2(35), 
	"Fechanacimiento" TIMESTAMP (7), 
	"Ciudad" NVARCHAR2(25), 
	"Email" NVARCHAR2(40)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table __EFMigrationsHistory
--------------------------------------------------------

  CREATE TABLE "NEXOSUSER"."__EFMigrationsHistory" 
   (	"MigrationId" NVARCHAR2(150), 
	"ProductVersion" NVARCHAR2(32)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table Libros
--------------------------------------------------------

  CREATE TABLE "NEXOSUSER"."Libros" 
   (	"IdLibro" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"Titulo" NVARCHAR2(40), 
	"Nopaginas" NUMBER(10,0), 
	"Ano" NUMBER(10,0), 
	"Genero" NVARCHAR2(30), 
	"Idautor" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into NEXOSUSER."Autors"
SET DEFINE OFF;
Insert into NEXOSUSER."Autors" ("Idautor","Nombre","Fechanacimiento","Ciudad","Email") values ('2','Stip',to_timestamp('10/09/21 05:15:11,382000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),'Vélez','stip@gmail.com');
Insert into NEXOSUSER."Autors" ("Idautor","Nombre","Fechanacimiento","Ciudad","Email") values ('7','Jorge',to_timestamp('15/09/21 08:44:00,000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),'Landázuri','jorge@gmail.com');
Insert into NEXOSUSER."Autors" ("Idautor","Nombre","Fechanacimiento","Ciudad","Email") values ('42','Lucas',to_timestamp('31/08/21 12:09:00,000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),'Bogotá','lucas@gmail.com');
REM INSERTING into NEXOSUSER."__EFMigrationsHistory"
SET DEFINE OFF;
Insert into NEXOSUSER."__EFMigrationsHistory" ("MigrationId","ProductVersion") values ('20210910170512_first migration','5.0.9');
REM INSERTING into NEXOSUSER."Libros"
SET DEFINE OFF;
Insert into NEXOSUSER."Libros" ("IdLibro","Titulo","Nopaginas","Ano","Genero","Idautor") values ('81','Libro 1','300','1900','Aventura','2');
Insert into NEXOSUSER."Libros" ("IdLibro","Titulo","Nopaginas","Ano","Genero","Idautor") values ('101','Libro 2','1020','2000','Ciencia Ficción','2');
Insert into NEXOSUSER."Libros" ("IdLibro","Titulo","Nopaginas","Ano","Genero","Idautor") values ('122','Libro 3','200','1923','Novela Policial','2');
Insert into NEXOSUSER."Libros" ("IdLibro","Titulo","Nopaginas","Ano","Genero","Idautor") values ('123','Libro 4','500','2021','Cuentos','2');
--------------------------------------------------------
--  DDL for Index PK_Autors
--------------------------------------------------------

  CREATE UNIQUE INDEX "NEXOSUSER"."PK_Autors" ON "NEXOSUSER"."Autors" ("Idautor") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_Libros
--------------------------------------------------------

  CREATE UNIQUE INDEX "NEXOSUSER"."PK_Libros" ON "NEXOSUSER"."Libros" ("IdLibro") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK___EFMigrationsHistory
--------------------------------------------------------

  CREATE UNIQUE INDEX "NEXOSUSER"."PK___EFMigrationsHistory" ON "NEXOSUSER"."__EFMigrationsHistory" ("MigrationId") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IX_Libros_Idautor
--------------------------------------------------------

  CREATE INDEX "NEXOSUSER"."IX_Libros_Idautor" ON "NEXOSUSER"."Libros" ("Idautor") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table Autors
--------------------------------------------------------

  ALTER TABLE "NEXOSUSER"."Autors" MODIFY ("Idautor" NOT NULL ENABLE);
  ALTER TABLE "NEXOSUSER"."Autors" MODIFY ("Nombre" NOT NULL ENABLE);
  ALTER TABLE "NEXOSUSER"."Autors" MODIFY ("Fechanacimiento" NOT NULL ENABLE);
  ALTER TABLE "NEXOSUSER"."Autors" MODIFY ("Ciudad" NOT NULL ENABLE);
  ALTER TABLE "NEXOSUSER"."Autors" MODIFY ("Email" NOT NULL ENABLE);
  ALTER TABLE "NEXOSUSER"."Autors" ADD CONSTRAINT "PK_Autors" PRIMARY KEY ("Idautor")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table __EFMigrationsHistory
--------------------------------------------------------

  ALTER TABLE "NEXOSUSER"."__EFMigrationsHistory" MODIFY ("MigrationId" NOT NULL ENABLE);
  ALTER TABLE "NEXOSUSER"."__EFMigrationsHistory" MODIFY ("ProductVersion" NOT NULL ENABLE);
  ALTER TABLE "NEXOSUSER"."__EFMigrationsHistory" ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table Libros
--------------------------------------------------------

  ALTER TABLE "NEXOSUSER"."Libros" MODIFY ("IdLibro" NOT NULL ENABLE);
  ALTER TABLE "NEXOSUSER"."Libros" MODIFY ("Titulo" NOT NULL ENABLE);
  ALTER TABLE "NEXOSUSER"."Libros" MODIFY ("Nopaginas" NOT NULL ENABLE);
  ALTER TABLE "NEXOSUSER"."Libros" MODIFY ("Ano" NOT NULL ENABLE);
  ALTER TABLE "NEXOSUSER"."Libros" MODIFY ("Genero" NOT NULL ENABLE);
  ALTER TABLE "NEXOSUSER"."Libros" MODIFY ("Idautor" NOT NULL ENABLE);
  ALTER TABLE "NEXOSUSER"."Libros" ADD CONSTRAINT "PK_Libros" PRIMARY KEY ("IdLibro")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table Libros
--------------------------------------------------------

  ALTER TABLE "NEXOSUSER"."Libros" ADD CONSTRAINT "FK_Libros_Autors_Idautor" FOREIGN KEY ("Idautor")
	  REFERENCES "NEXOSUSER"."Autors" ("Idautor") ON DELETE CASCADE ENABLE;
